# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9c04c371986c8cf87f91ffb55d78b6518ab45fdba9338cd60d54673ffb5a2243fd255cbb2b576c5c7eef920f9845e9afbe98a691b9fd63cde66a91f20d703722

test:
  secret_key_base: c3933895684d2f50f7f4b8082e39a0621a5dcccf21c5d65863fdda96698bdf89cb71533a4be8bd28ed5b5bf514a8be69685f82d42097a16f0cc358bf5472298b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
